### ISSUE TITLE
Add Sitemap

### ISSUE THREAD

**Issue by jdorfman** [curiefense/curiefense.github.io#33]
![image](https://user-images.githubusercontent.com/398230/117702239-19fd6f80-b17d-11eb-9db9-13cd521765d6.png)

**Comment by aaryanporwal** [comment]
We can use [this](https://github.com/netlify-labs/netlify-plugin-sitemap) plugin to get sitemaps on each build.

**Comment by jdorfman** [comment]
Done. Great find @aaryanporwal 
 
![Image 2021-07-01 at 2 09 52 PM](https://user-images.githubusercontent.com/398230/124189740-0e8c3d80-da76-11eb-83a6-49ee1ed3bf02.jpg)

**Comment by jdorfman** [comment]
![Image 2021-07-01 at 2 13 25 PM](https://user-images.githubusercontent.com/398230/124190087-8f4b3980-da76-11eb-8bf9-5d16e196a444.jpg)
